import {test,expect} from '@playwright/test';import fs from 'node:fs';
const env=Object.fromEntries(fs.readFileSync('runtime/.env','utf8').trim().split('\n').map(line=>line.split(/=(.*)/s).slice(0,2)));
test('Portal is a real scoped task UI; errors, corrections and logout work',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('./');await expect(page.getByRole('heading',{level:1})).toHaveText('Terminal Flow Control');
 await page.getByLabel('Bearer-token').fill(env.ROLEOS_READER_TOKEN);await page.getByRole('button',{name:'Verbind & vernieuw'}).click();await expect(page.locator('#feedback')).toHaveText('Actuele gegevens opgehaald.');await page.screenshot({path:'runtime/portal-desktop.png',fullPage:true});
 await page.getByLabel('Voertuig-ID').fill('DEMO0000000000001');await page.getByLabel('Reden').fill('UI authorization check');await page.getByRole('button',{name:'Corrigeer met audit'}).click();await expect(page.locator('#feedback')).toContainText('403');
 await page.getByRole('button',{name:'Token wissen'}).click();await expect(page.getByLabel('Bearer-token')).toHaveValue('');await expect(page.locator('#vehicles')).toBeEmpty();
 await page.getByLabel('Bearer-token').fill(env.ROLEOS_ALPHA_TOKEN);await page.getByLabel('JSON-profiel').fill(JSON.stringify({message_id:'ui-'+Date.now(),event_key:'ui-'+Date.now(),partner_id:'ALPHA',site_id:'ZEE',vin:('U'+Date.now().toString().padStart(16,'0')),event_type:'ARRIVAL',location:'ZEE-A01',event_at:new Date().toISOString(),expected_version:0}));await page.getByRole('button',{name:'Verstuur bericht'}).click();await expect(page.locator('#feedback')).toContainText('RECEIVED');
 await page.getByLabel('Bearer-token').fill(env.ROLEOS_OPERATOR_TOKEN);await page.getByRole('button',{name:'Verbind & vernieuw'}).click();await expect(page.locator('#vehicles tr')).not.toHaveCount(0);await expect(page.locator('#report')).toContainText('vehicle_count');expect(errors).toEqual([]);
});
test('Mobile controls/table scrolling remain usable at390px',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('./');await expect(page.getByRole('heading',{level:1})).toBeVisible();await page.getByLabel('Bearer-token').fill(env.ROLEOS_READER_TOKEN);await page.getByRole('button',{name:'Verbind & vernieuw'}).click();await expect(page.locator('#feedback')).toHaveText('Actuele gegevens opgehaald.');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'runtime/portal-mobile.png',fullPage:true});});
