const $=id=>document.getElementById(id);
async function api(path,method='GET',body){const response=await fetch(`.${path}`,{method,headers:{Authorization:`Bearer ${$('token').value}`,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});const value=await response.json();if(!response.ok)throw Error(`${response.status} · ${value.error}: ${value.message}`);return value;}
function table(id,rows,fields){const root=$(id);root.replaceChildren();for(const row of rows){const tr=document.createElement('tr');for(const field of fields){const td=document.createElement('td');td.textContent=typeof field==='function'?field(row):String(row[field]??'—');tr.append(td);}root.append(tr);}}
async function refresh(){try{const [vehicles,messages,report]=await Promise.all([api('/api/vehicles'),api('/api/messages'),api('/api/reports/occupancy')]);table('vehicles',vehicles,['vin',r=>`${r.partner_id} / ${r.site_id}`,'location_id',r=>`${r.state} / ${r.hold_flag?'HOLD':'vrij'}`,'version']);table('messages',messages,['event_key','site_id','status','attempts',r=>`${r.last_error||'—'} · ${r.id}`]);$('report').textContent=JSON.stringify(report,null,2);try{const metrics=await api('/api/metrics');$('metrics').replaceChildren();for(const [key,label] of [['messages_received','Ontvangen / wachtend'],['messages_retry_wait','Retry backlog'],['messages_rejected','Afgewezen'],['oldest_pending_seconds','Oudste backlog (s)'],['ack_pending','ACK nog open']]){const box=document.createElement('div');box.className='metric';const count=document.createElement('strong');count.textContent=metrics[key];const caption=document.createElement('span');caption.textContent=label;box.append(count,caption);$('metrics').append(box);}}catch{ $('metrics').textContent='Metrics vereisen reader/operator/admin; partnerdata is beschikbaar.'; }$('feedback').textContent='Actuele gegevens opgehaald.';}catch(e){$('feedback').textContent=e.message;}}
$('connect').addEventListener('click',refresh);$('logout').addEventListener('click',()=>{$('token').value='';$('vehicles').replaceChildren();$('messages').replaceChildren();$('metrics').replaceChildren();$('report').textContent='Token gewist.';$('feedback').textContent='Token en geladen gegevens gewist.';});
$('send').addEventListener('click',async()=>{try{const result=await api('/api/messages','POST',JSON.parse($('payload').value));$('feedback').textContent=JSON.stringify(result); }catch(e){$('feedback').textContent=e.message;}});
$('correct').addEventListener('click',async()=>{try{await api(`/api/vehicles/${encodeURIComponent($('vin').value)}/location`,'PUT',{expected_version:Number($('version').value),location:$('location').value,reason:$('reason').value});await refresh();$('feedback').textContent='Correctie uitgevoerd en geaudit.';}catch(e){$('feedback').textContent=e.message;}});
$('control').addEventListener('click',async()=>{try{await api('/api/admin/controls','PATCH',{worker_paused:$('paused').value==='true'});$('feedback').textContent='Labcontrol aangepast; audit bijgewerkt.';}catch(e){$('feedback').textContent=e.message;}});
$('payload').value=JSON.stringify({message_id:'portal-demo-1',event_key:'portal-arrival-1',partner_id:'ALPHA',site_id:'ZEE',vin:'DEMO0000000000001',event_type:'ARRIVAL',location:'ZEE-A01',event_at:new Date().toISOString(),expected_version:0},null,2);
fetch('./health').then(r=>r.json()).then(h=>{$('health').textContent=`${h.status} · v${h.version}`;}).catch(()=>{$('health').textContent='Dienst niet bereikbaar';});
